-- This file has moved.
--
-- The canonical schema now lives at  internal/db/schema.sql
-- so it can be embedded directly into the simulator binary via
-- //go:embed (see internal/db/schema.go). The simulator applies it
-- automatically the first time it runs against an empty database, and
-- on demand via the `-reset-schema` flag.
--
-- To apply it manually with psql:
--   psql "$DATABASE_URL" -f internal/db/schema.sql
--
-- Or, if you have the CedarDB container running and prefer to use the
-- psql CLI bundled in its image:
--   docker exec -i f1-cedardb psql -U postgres -d cedar \
--       < internal/db/schema.sql
