services:
  loader:
    build:
      context: loader
      dockerfile: Dockerfile
    volumes:
      - data:/app/data
  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - data:/data
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U postgres -d postgres -h 127.0.0.1 -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 10
  cedar:
    container_name: cedar
    image: cedardb/cedardb
    restart: always
    environment:
      CEDAR_DB: postgres
      CEDAR_USER: postgres
      CEDAR_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/data
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U postgres -d postgres -h 127.0.0.1 -p 5432"]
      interval: 10s
      timeout: 1s
      retries: 10
  grafana:
    image: grafana/grafana:12.0.0
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=100ms
    ports:
      - 3000:3000
    depends_on:
      - cedar
      - postgres
    volumes:
      - ./grafana:/etc/grafana/provisioning
  client-cedar:
    build:
      context: client
      dockerfile: Dockerfile
    depends_on:
      loader:
        condition: service_completed_successfully
      cedar:
        condition: service_healthy
    volumes:
      - data:/nasdaq/data
  client-postgres:
    build:
      context: client
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
    depends_on:
      loader:
        condition: service_completed_successfully
      cedar:
        condition: service_healthy
    volumes:
      - data:/nasdaq/data

volumes:
  data:
