{
 "title": "NASDAQ-POSTGRES",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "stock", "label": "Stock", "query": "select name from stocks" },
   {
    "name": "bins",
    "query": "1s : 1000,2s : 2000,5s : 5000,10s : 10000,30s : 20000,1min : 60000,5min : 300000,10min : 600000"
   },
   { "name": "width", "label": "Order book width", "query": "1.05" },
   {
    "name": "timeOffset",
    "query": "select (extract(EPOCH from current_timestamp) - extract(EPOCH from current_date + ( max(timestamp)/(1000*1000) * interval '1 millisecond')))::integer as delay from orders o"
   }
  ]
 },
 "panels": [
  {
   "title": "Order book depth for ${stock}",
   "type": "trend",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "repeat": "stock",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with orderdepth as ( \r\n    select price, side, sum(quantity) as quantity\r\n    from orderbook o, stocks s \r\n    where o.stockId = s.stockId\r\n    and s.name in (${stock})\r\n    group by price, side\r\n),\r\ncumulative_sell as (\r\n    select price, side as metric, sum(quantity) over (order by price asc) as sum\r\n    from orderdepth\r\n    where quantity > 0\r\n    and side = 'SELL'\r\n),\r\ncumulative_buy as (\r\n    select price, side as metric, sum(quantity) over (order by price desc) as sum\r\n    from orderdepth\r\n    where quantity > 0\r\n    and side = 'BUY'\r\n),\r\ncumulative as (\r\n    select * from cumulative_sell where sum > 0 and price < ${width} * (select min(price) from cumulative_sell)\r\n    union all\r\n    select * from cumulative_buy where sum > 0 and price > 1::numeric/${width} * (select max(price) from cumulative_buy)\r\n)\r\nselect * from cumulative order by price asc;"
    }
   ]
  },
  {
   "title": "New",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) / 1 as new\r\nfrom  orders o \r\nwhere prevOrder is null\r\nand o.timestamp > (select max(e.timestamp) from executions e) - 1::bigint * 1000 * 1000 * 1000;"
    }
   ]
  },
  {
   "title": "Executed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) / 1 as executed\r\nfrom  executions e \r\nwhere e.timestamp > (select max(e2.timestamp) from executions e2) - 1::bigint * 1000 * 1000 * 1000;"
    }
   ]
  },
  {
   "title": "Canceled",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) / 1 as canceled\r\nfrom  cancellations c \r\nwhere c.timestamp > (select max(e.timestamp) from executions e) - 1::bigint * 1000 * 1000 * 1000;"
    }
   ]
  },
  {
   "title": "Updated",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) / 1 as new\r\nfrom  orders o \r\nwhere prevOrder is not null\r\nand o.timestamp > (select max(e.timestamp) from executions e) - 1::bigint * 1000 * 1000 * 1000;"
    }
   ]
  }
 ]
}