{
 "title": "NASDAQ-Comparison",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "stock", "label": "Stock", "query": "select name from stocks" },
   {
    "name": "bins",
    "query": "1s : 1000,2s : 2000,5s : 5000,10s : 10000,30s : 20000,1min : 60000,5min : 300000,10min : 600000"
   },
   { "name": "width", "label": "Order book width", "query": "1.05" },
   {
    "name": "timeOffset",
    "query": "select (extract(EPOCH from current_timestamp) - extract(EPOCH from current_date + ( max(timestamp)/(1000*1000) * interval '1 millisecond')))::integer as delay from orders o"
   }
  ]
 },
 "panels": [
  {
   "title": "Largest Orders - CedarDB 🌲",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "100 biggest trades in current time range",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "select EXTRACT(EPOCH FROM current_date + (e.timestamp/(1000*1000) * interval '1 millisecond')) as time, s.name, o.side, e.quantity, coalesce(e.price, o.price) as price, e.quantity * coalesce(e.price, o.price) as volume \r\nfrom executions e, stocks s, orders o \r\nwhere e.orderid = o.orderid and o.stockid = s.stockid\r\nand e.timestamp >= (${__from:date:seconds} - extract(epoch from current_date)) * 1000 * 1000 * 1000\r\nand e.timestamp < (${__to:date:seconds} - extract(epoch from current_date)) * 1000 * 1000 * 1000\r\norder by volume desc\r\nlimit 100;"
      }
     ]
    }
   ]
  },
  {
   "title": "Largest Orders - Postgres 🐘",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "100 biggest trades in current time range",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "rawSql": "select EXTRACT(EPOCH FROM current_date + (e.timestamp/(1000*1000) * interval '1 millisecond')) as time, s.name, o.side, e.quantity, coalesce(e.price, o.price) as price, e.quantity * coalesce(e.price, o.price) as volume \r\nfrom executions e, stocks s, orders o \r\nwhere e.orderid = o.orderid and o.stockid = s.stockid\r\nand e.timestamp >= (${__from:date:seconds} - extract(epoch from current_date)) * 1000 * 1000 * 1000\r\nand e.timestamp < (${__to:date:seconds} - extract(epoch from current_date)) * 1000 * 1000 * 1000\r\norder by volume desc\r\nlimit 100;"
      }
     ]
    }
   ]
  },
  {
   "title": "Orderbook - CedarDB 🌲",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Order book depth for ${stock}",
     "type": "trend",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
     "repeat": "stock",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "with orderdepth as ( \r\n    select price, side, sum(quantity) as quantity\r\n    from orderbook o, stocks s \r\n    where o.stockId = s.stockId\r\n    and s.name in (${stock})\r\n    group by price, side\r\n),\r\ncumulative_sell as (\r\n    select price, side as metric, sum(quantity) over (order by price asc) as sum\r\n    from orderdepth\r\n    where quantity > 0\r\n    and side = 'SELL'\r\n),\r\ncumulative_buy as (\r\n    select price, side as metric, sum(quantity) over (order by price desc) as sum\r\n    from orderdepth\r\n    where quantity > 0\r\n    and side = 'BUY'\r\n),\r\ncumulative as (\r\n    select * from cumulative_sell where sum > 0 and price < ${width} * (select min(price) from cumulative_sell)\r\n    union all\r\n    select * from cumulative_buy where sum > 0 and price > 1::numeric/${width} * (select max(price) from cumulative_buy)\r\n)\r\nselect * from cumulative order by price asc;"
      }
     ]
    }
   ]
  },
  {
   "title": "Orderbook - Postgres 🐘",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Order book depth for ${stock}",
     "type": "trend",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 105 },
     "repeat": "stock",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "with orderdepth as ( \r\n    select price, side, sum(quantity) as quantity\r\n    from orderbook o, stocks s \r\n    where o.stockId = s.stockId\r\n    and s.name in (${stock})\r\n    group by price, side\r\n),\r\ncumulative_sell as (\r\n    select price, side as metric, sum(quantity) over (order by price asc) as sum\r\n    from orderdepth\r\n    where quantity > 0\r\n    and side = 'SELL'\r\n),\r\ncumulative_buy as (\r\n    select price, side as metric, sum(quantity) over (order by price desc) as sum\r\n    from orderdepth\r\n    where quantity > 0\r\n    and side = 'BUY'\r\n),\r\ncumulative as (\r\n    select * from cumulative_sell where sum > 0 and price < ${width} * (select min(price) from cumulative_sell)\r\n    union all\r\n    select * from cumulative_buy where sum > 0 and price > 1::numeric/${width} * (select max(price) from cumulative_buy)\r\n)\r\nselect * from cumulative order by price asc;"
      }
     ]
    }
   ]
  },
  {
   "title": "Exchange Activity - CedarDB 🌲",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "New Orders",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(*) / 1 as new\r\nfrom  orders o \r\nwhere prevOrder is null\r\nand o.timestamp > (select max(e.timestamp) from executions e) - 1::bigint * 1000 * 1000 * 1000;"
      }
     ]
    },
    {
     "title": "Updated Orders",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 3, "x": 3, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(*) / 1 as new\r\nfrom  orders o \r\nwhere prevOrder is not null\r\nand o.timestamp > (select max(e.timestamp) from executions e) - 1::bigint * 1000 * 1000 * 1000;"
      }
     ]
    },
    {
     "title": "Executions",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 3, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(*) / 1 as executed\r\nfrom  executions e \r\nwhere e.timestamp > (select max(e2.timestamp) from executions e2) - 1::bigint * 1000 * 1000 * 1000;"
      }
     ]
    },
    {
     "title": "Cancellations",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 3, "x": 9, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(*) / 1 as canceled\r\nfrom  cancellations c \r\nwhere c.timestamp > (select max(e.timestamp) from executions e) - 1::bigint * 1000 * 1000 * 1000;"
      }
     ]
    },
    {
     "title": "Latest Event",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT to_char(to_timestamp(max(t) / 1e9), 'HH:MI:SS') as latest_time from (\n  SELECT max(\"timestamp\") as t FROM orders\n  UNION\n  SELECT max(\"timestamp\") as t FROM executions\n  UNION\n  SELECT max(\"timestamp\") as t FROM cancellations \n)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Exchange Activity - Postgres 🐘",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "New Orders",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(*) / 1 as new\r\nfrom  orders o \r\nwhere prevOrder is null\r\nand o.timestamp > (select max(e.timestamp) from executions e) - 1::bigint * 1000 * 1000 * 1000;"
      }
     ]
    },
    {
     "title": "Updated Orders",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 3, "x": 3, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(*) / 1 as new\r\nfrom  orders o \r\nwhere prevOrder is not null\r\nand o.timestamp > (select max(e.timestamp) from executions e) - 1::bigint * 1000 * 1000 * 1000;"
      }
     ]
    },
    {
     "title": "Executions",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 3, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(*) / 1 as executed\r\nfrom  executions e \r\nwhere e.timestamp > (select max(e2.timestamp) from executions e2) - 1::bigint * 1000 * 1000 * 1000;"
      }
     ]
    },
    {
     "title": "Cancellations",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 3, "x": 9, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(*) / 1 as canceled\r\nfrom  cancellations c \r\nwhere c.timestamp > (select max(e.timestamp) from executions e) - 1::bigint * 1000 * 1000 * 1000;"
      }
     ]
    },
    {
     "title": "Latest Event ",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT to_char(to_timestamp(max(t) / 1e9), 'HH:MI:SS') as latest_time from (\n  SELECT max(\"timestamp\") as t FROM orders\n  UNION\n  SELECT max(\"timestamp\") as t FROM executions\n  UNION\n  SELECT max(\"timestamp\") as t FROM cancellations \n)\n"
      }
     ]
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Usage (Cores)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (\n  rate(container_cpu_usage_seconds_total{\n    container_label_com_docker_compose_service=~\"cedar|postgres\"\n  }[15s])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (GB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (\n  container_memory_usage_bytes{\n    container_label_com_docker_compose_service=~\"cedar|postgres\"\n  }\n) / 1024^3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O (MB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (\n  rate(container_fs_writes_bytes_total{\n    container_label_com_docker_compose_service=~\"cedar|postgres\"\n  }[15s])\n) / 1024^2",
     "legendFormat": "{{container_label_com_docker_compose_service}} - writes"
    },
    {
     "expr": "sum by (container_label_com_docker_compose_service) (\n  rate(container_fs_reads_bytes_total{\n    container_label_com_docker_compose_service=~\"cedar|postgres\"\n  }[15s])\n) / 1024^2",
     "legendFormat": "{{container_label_com_docker_compose_service}} - reads"
    }
   ]
  }
 ]
}