apiVersion: 1

deleteDatasources:
  - name: cedar
    orgId: 1
  - name: postgres
    orgId: 1
  - name: prometheus
    orgId: 1

datasources:
  - name: cedar
    type: grafana-postgresql-datasource
    access: proxy
    uid: fdl2zuq913klcb
    orgId: 1
    url: cedar:5432
    user: postgres
    database: postgres
    basicAuth: false
    secureJsonData:
      password: postgres
    isDefault: true
    jsonData:
      connMaxLifetime: 14400
      database: postgres
      maxIdleConns: 100
      maxIdleConnsAuto: true
      maxOpenConns: 100
      postgresVersion: 1500
      sslmode: disable
      timeInterval: 10ms
    version: 1
    editable: true
  - name: postgres
    type: grafana-postgresql-datasource
    access: proxy
    uid: fdl2zuq913klcc
    orgId: 1
    url: postgres:5432
    user: postgres
    database: postgres
    basicAuth: false
    secureJsonData:
      password: postgres
    isDefault: false
    jsonData:
      connMaxLifetime: 14400
      database: postgres
      maxIdleConns: 100
      maxIdleConnsAuto: true
      maxOpenConns: 100
      postgresVersion: 1500
      sslmode: disable
      timeInterval: 10ms
    version: 1
    editable: true
  - name: prometheus
    type: prometheus
    access: proxy
    uid: fdl2zuq913klcd
    orgId: 1
    url: http://prometheus:9090
    isDefault: false
    jsonData:
      httpMethod: POST
    version: 1
    editable: true
